JNG-2856 Added hide function to JudoTab.
BlackBeltTechnology/judo-flutter-components pull request #15
Opened 2021-07-09 12:16 UTC by rolandknobloch

2021-07-09 12:34 UTC, robertcsakany approved these changes

2021-07-12 10:38 UTC, noherczeg requested changes

2021-07-12 10:38 UTC, noherczeg commented on lib/src/judo_tab.dart
> +    this.hiddenTabs,
Optional parameters *MUST* have default values. This helps us by negating the need of internal null checks!

2021-07-12 11:04 UTC, noherczeg commented on lib/src/judo_tab.dart
> +    this.hiddenTabs,
Never mind, language has difficulties working as expected.

2021-07-12 11:04 UTC, noherczeg approved these changes

2021-07-12 11:05 UTC, merged