Feature/jng 2594 create action group button
BlackBeltTechnology/judo-flutter-components pull request #25
Opened 2021-08-23 21:10 UTC by fruska

2021-08-23 21:47 UTC, robertcsakany approved these changes

2021-08-24 13:35 UTC, noherczeg approved these changes

2021-08-24 13:48 UTC, rolandknobloch requested changes

2021-08-24 13:48 UTC, rolandknobloch commented on lib/src/judo_app_bar_button.dart
> -    Key key,
please dont remove key property from components

2021-08-24 13:48 UTC, rolandknobloch commented on lib/src/judo_app_bar_button.dart
> -  }) : super(key: key);
and the super constructor call with key

2021-08-24 14:03 UTC, rolandknobloch approved these changes

2021-08-24 14:20 UTC, merged