Feature/jng 2930 action group for tables
BlackBeltTechnology/judo-flutter-components pull request #26
Opened 2021-09-03 17:15 UTC by fruska

A new attribute is added to table which is used to create the popup action button in the header cell of the last  column.
The shape of the popup menu is changed to a slightly rounded rectangle for a more satisfying visual experience.

2021-09-03 17:31 UTC, robertcsakany approved these changes

2021-09-03 23:10 UTC, noherczeg requested changes

2021-09-03 23:10 UTC, noherczeg commented on lib/src/judo_table.dart
> +    this.tableActions,
We should initialize this param with a default value. This will negate the need of internal null checks, and prevents potential NPE-s.

2021-09-08 15:47 UTC, noherczeg requested changes

2021-09-08 15:47 UTC, noherczeg commented on lib/src/judo_table.dart
> +          dataInfo.getColumns(onAdd, onSort) : getColumns(),
`tableActions.isEmpty ? dataInfo.getColumns(onAdd, onSort) : [...dataInfo.getColumns(onAdd, onSort), DataColumn(label: getPopupButton())]`

2021-09-09 07:52 UTC, noherczeg approved these changes

2021-09-09 13:32 UTC, merged