JNG-3040 Removed data and formatter properties from JudoLink.
BlackBeltTechnology/judo-flutter-components pull request #38
Opened 2021-11-05 10:30 UTC by rolandknobloch

Added new property to JudoLink: labelList.
Added generic formatting method to JudoLink.

2021-11-05 14:07 UTC, noherczeg requested changes

2021-11-05 14:07 UTC, noherczeg commented on lib/src/judo_link.dart
> +    return ret;
`labelList.where((l) => l != null && l.isNotEmpty).join(' ')`

2021-11-08 09:16 UTC, noherczeg approved these changes

2021-11-09 10:02 UTC, fruska approved these changes

2021-11-09 12:21 UTC, merged