Feature/jng 2347 row actions in table have to be modelled
BlackBeltTechnology/judo-flutter-components pull request #42
Opened 2021-11-22 20:04 UTC by rolandknobloch

2021-11-22 20:15 UTC, robertcsakany approved these changes

2021-11-22 20:22 UTC, robertcsakany approved these changes

2021-11-23 17:00 UTC, noherczeg requested changes

2021-11-23 17:00 UTC, noherczeg commented on lib/src/judo_table.dart
> +    this.rowActionList,
Please provide default value!

2021-11-24 16:08 UTC, merged